[env:teensy40]
platform = teensy
board = teensy40
framework = arduino
monitor_speed = 115200

lib_extra_dirs =
  ../..

lib_deps =
  ppedro74/SerialCommands@^2.2.0
  ; When running inside this repository, PlatformIO will use the local library automatically.
